# Generated by Django 2.1.3 on 2019-04-27 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='user',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
